class JobPost {
  final String id;
  final String company_id;
  final String job_title;
  final String job_level;
  final String vacancy_count;
  final String employment_type;
  final String salary;
  final String job_location;
  final String deadline;
  final String education_level;
  final String experience;
  final String skills;
  final String specifications;
  final String views;
  final String created_at;
  final String updated_at;

  JobPost({
    required this.id,
    required this.company_id,
    required this.job_title,
    required this.job_level,
    required this.vacancy_count,
    required this.employment_type,
    required this.salary,
    required this.job_location,
    required this.deadline,
    required this.education_level,
    required this.experience,
    required this.skills,
    required this.specifications,
    required this.views,
    required this.created_at,
    required this.updated_at,
  });

  static List<JobPost> jobPostsList() {
    return [
      JobPost(
        id: '1',
        company_id: '1',
        job_title: 'Php laravel developer',
        job_level: 'Senior level',
        vacancy_count: '5',
        employment_type: 'full time',
        salary: '20k - 50k',
        job_location: 'Karachi',
        deadline: '2023-11-07 19:11:59',
        education_level: 'bachelors',
        experience: '2 years',
        skills: 'Team player, Active listener',
        specifications: '<p><\/p>',
        views: '1',
        created_at: '2023-11-05 19:11:59',
        updated_at: '2023-11-05 19:11:59',
      ),
      JobPost(
        id: '2',
        company_id: '1',
        job_title: 'Marketing Expert',
        job_level: 'Senior level',
        vacancy_count: '8',
        employment_type: 'full time',
        salary: '20k - 50k',
        job_location: 'Lahore',
        deadline: '2023-12-20 20:56:15',
        education_level: 'bachelors',
        experience: '2 years',
        skills: 'Team player, Active listener',
        specifications: '<p><\/p>',
        views: '7',
        created_at: '2023-11-05 19:12:00',
        updated_at: '2023-12-20 15:56:15',
      ),
      JobPost(
        id: '3',
        company_id: '1',
        job_title: 'Professional designer',
        job_level: 'Top level',
        vacancy_count: '3',
        employment_type: 'Part time',
        salary: '20k - 50k',
        job_location: 'Islamabad',
        deadline: '2023-12-20 20:58:01',
        education_level: 'bachelors',
        experience: '2 years',
        skills: 'Team player, Active listener',
        specifications: '<p><\/p>',
        views: '6',
        created_at: '2023-11-05 19:12:00',
        updated_at: '2023-12-20 15:58:01',
      ),
      JobPost(
        id: '4',
        company_id: '2',
        job_title: 'Mobile App Developer',
        job_level: 'Mid level',
        vacancy_count: '3',
        employment_type: 'Contract',
        salary: '30k - 60k',
        job_location: 'Rawalpindi',
        deadline: '2023-12-25 10:30:00',
        education_level: 'bachelors',
        experience: '3 years',
        skills: 'Flutter, Android, iOS',
        specifications: '<p><\/p>',
        views: '4',
        created_at: '2023-11-10 14:45:00',
        updated_at: '2023-12-23 18:20:30',
      ),
      JobPost(
        id: '5',
        company_id: '2',
        job_title: 'Data Scientist',
        job_level: 'Senior level',
        vacancy_count: '2',
        employment_type: 'Full time',
        salary: '40k - 80k',
        job_location: 'Faisalabad',
        deadline: '2023-12-30 15:00:00',
        education_level: 'masters',
        experience: '5 years',
        skills: 'Machine Learning, Python',
        specifications: '<p><\/p>',
        views: '8',
        created_at: '2023-11-15 09:30:00',
        updated_at: '2023-12-28 12:45:20',
      ),
      JobPost(
        id: '6',
        company_id: '3',
        job_title: 'UX/UI Designer',
        job_level: 'Mid level',
        vacancy_count: '4',
        employment_type: 'Part time',
        salary: '25k - 45k',
        job_location: 'Multan',
        deadline: '2023-12-22 12:45:00',
        education_level: 'bachelors',
        experience: '3 years',
        skills: 'UI/UX Design, Adobe XD',
        specifications: '<p><\/p>',
        views: '5',
        created_at: '2023-11-08 17:15:00',
        updated_at: '2023-12-20 10:10:45',
      ),
      JobPost(
        id: '7',
        company_id: '3',
        job_title: 'Software Engineer',
        job_level: 'Junior level',
        vacancy_count: '6',
        employment_type: 'Internship',
        salary: '15k - 25k',
        job_location: 'Sialkot',
        deadline: '2024-01-05 09:00:00',
        education_level: 'bachelors',
        experience: 'Fresh graduate',
        skills: 'Java, C++, OOP',
        specifications: '<p><\/p>',
        views: '3',
        created_at: '2023-11-25 08:00:00',
        updated_at: '2023-12-30 16:30:15',
      ),
      JobPost(
        id: '8',
        company_id: '4',
        job_title: 'Content Writer',
        job_level: 'Entry level',
        vacancy_count: '10',
        employment_type: 'Freelance',
        salary: 'Variable',
        job_location: 'Quetta',
        deadline: '2023-12-18 16:20:00',
        education_level: 'bachelors',
        experience: 'Fresh graduate',
        skills: 'Content writing, SEO',
        specifications: '<p><\/p>',
        views: '2',
        created_at: '2023-11-20 11:30:00',
        updated_at: '2023-12-15 14:10:30',
      ),
      JobPost(
        id: '9',
        company_id: '4',
        job_title: 'Graphic Designer',
        job_level: 'Junior level',
        vacancy_count: '5',
        employment_type: 'Full time',
        salary: '25k - 40k',
        job_location: 'Peshawar',
        deadline: '2023-12-12 11:15:00',
        education_level: 'bachelors',
        experience: '1 year',
        skills: 'Adobe Photoshop, Illustrator',
        specifications: '<p><\/p>',
        views: '6',
        created_at: '2023-11-15 14:30:00',
        updated_at: '2023-12-10 10:25:45',
      ),
      JobPost(
        id: '10',
        company_id: '5',
        job_title: 'Network Administrator',
        job_level: 'Mid level',
        vacancy_count: '3',
        employment_type: 'Contract',
        salary: '35k - 60k',
        job_location: 'Larkana',
        deadline: '2023-12-28 13:30:00',
        education_level: 'bachelors',
        experience: '4 years',
        skills: 'Cisco, Network Security',
        specifications: '<p><\/p>',
        views: '8',
        created_at: '2023-11-20 16:45:00',
        updated_at: '2023-12-25 09:55:30',
      ),
      JobPost(
        id: '11',
        company_id: '6',
        job_title: 'HR Specialist',
        job_level: 'Senior level',
        vacancy_count: '2',
        employment_type: 'Full time',
        salary: '40k - 70k',
        job_location: 'Hyderabad',
        deadline: '2023-12-15 09:00:00',
        education_level: 'masters',
        experience: '5 years',
        skills: 'Recruitment, Employee Relations',
        specifications: '<p><\/p>',
        views: '7',
        created_at: '2023-11-12 12:00:00',
        updated_at: '2023-12-10 16:20:45',
      ),
      JobPost(
        id: '12',
        company_id: '7',
        job_title: 'Quality Assurance Engineer',
        job_level: 'Mid level',
        vacancy_count: '4',
        employment_type: 'Part time',
        salary: '30k - 50k',
        job_location: 'Karachi',
        deadline: '2023-12-22 14:45:00',
        education_level: 'bachelors',
        experience: '3 years',
        skills: 'Manual Testing, Automation Testing',
        specifications: '<p><\/p>',
        views: '5',
        created_at: '2023-11-18 17:30:00',
        updated_at: '2023-12-20 11:15:30',
      ),
      JobPost(
        id: '13',
        company_id: '8',
        job_title: 'Front-end Developer',
        job_level: 'Junior level',
        vacancy_count: '6',
        employment_type: 'Internship',
        salary: '15k - 25k',
        job_location: 'Multan',
        deadline: '2024-01-05 09:00:00',
        education_level: 'bachelors',
        experience: 'Fresh graduate',
        skills: 'HTML, CSS, JavaScript',
        specifications: '<p><\/p>',
        views: '3',
        created_at: '2023-11-25 08:00:00',
        updated_at: '2023-12-30 16:30:15',
      ),
      JobPost(
        id: '14',
        company_id: '9',
        job_title: 'Business Analyst',
        job_level: 'Mid level',
        vacancy_count: '7',
        employment_type: 'Freelance',
        salary: 'Variable',
        job_location: 'Islamabad',
        deadline: '2023-12-18 16:20:00',
        education_level: 'masters',
        experience: '2 years',
        skills: 'Data Analysis, Requirements Gathering',
        specifications: '<p><\/p>',
        views: '2',
        created_at: '2023-11-20 11:30:00',
        updated_at: '2023-12-15 14:10:30',
      ),
      JobPost(
        id: '15',
        company_id: '10',
        job_title: 'Sales Executive',
        job_level: 'Entry level',
        vacancy_count: '10',
        employment_type: 'Full time',
        salary: '20k - 35k',
        job_location: 'Faisalabad',
        deadline: '2023-12-12 09:15:00',
        education_level: 'bachelors',
        experience: 'Fresh graduate',
        skills: 'Communication, Sales',
        specifications: '<p><\/p>',
        views: '6',
        created_at: '2023-11-15 14:30:00',
        updated_at: '2023-12-10 10:25:45',
      ),
      JobPost(
        id: '16',
        company_id: '11',
        job_title: 'Database Administrator',
        job_level: 'Senior level',
        vacancy_count: '3',
        employment_type: 'Contract',
        salary: '35k - 60k',
        job_location: 'Rawalpindi',
        deadline: '2023-12-28 13:30:00',
        education_level: 'bachelors',
        experience: '4 years',
        skills: 'SQL, Database Management',
        specifications: '<p><\/p>',
        views: '8',
        created_at: '2023-11-20 16:45:00',
        updated_at: '2023-12-25 09:55:30',
      ),
      JobPost(
        id: '17',
        company_id: '12',
        job_title: 'Project Manager',
        job_level: 'Senior level',
        vacancy_count: '2',
        employment_type: 'Full time',
        salary: '40k - 70k',
        job_location: 'Larkana',
        deadline: '2023-12-15 09:00:00',
        education_level: 'masters',
        experience: '5 years',
        skills: 'Project Management, Leadership',
        specifications: '<p><\/p>',
        views: '7',
        created_at: '2023-11-12 12:00:00',
        updated_at: '2023-12-10 16:20:45',
      ),
      // Add other JobPost instances here...
    ];
  }
}
